# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('post1', models.IntegerField(default=0)),
                ('post2', models.IntegerField(default=0)),
                ('post3', models.IntegerField(default=0)),
                ('post4', models.IntegerField(default=0)),
                ('post5', models.IntegerField(default=0)),
                ('post6', models.IntegerField(default=0)),
                ('post7', models.IntegerField(default=0)),
                ('post8', models.IntegerField(default=0)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
