# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 22:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20161216_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('newsletter_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('post1', models.IntegerField(default=0)),
                ('post2', models.IntegerField(default=0)),
                ('post3', models.IntegerField(default=0)),
                ('post4', models.IntegerField(default=0)),
                ('post5', models.IntegerField(default=0)),
                ('post6', models.IntegerField(default=0)),
                ('post7', models.IntegerField(default=0)),
                ('post8', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter_Sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('campaign_id', models.IntegerField(default=0)),
                ('sequence', models.IntegerField(default=0)),
                ('post1', models.IntegerField(default=0)),
                ('post2', models.IntegerField(default=0)),
                ('post3', models.IntegerField(default=0)),
                ('post4', models.IntegerField(default=0)),
                ('post5', models.IntegerField(default=0)),
                ('post6', models.IntegerField(default=0)),
                ('post7', models.IntegerField(default=0)),
                ('post8', models.IntegerField(default=0)),
                ('post8_visit', models.IntegerField(default=0)),
                ('post8_shared', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='username',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
