# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_auto_20161216_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='Inactive', max_length=10),
        ),
    ]
